lessons/network-configuration/arp-command.md, lessons/network-configuration/network-interfaces.md, lessons/network-configuration/route.md, lessons/text-fu/env-environment.md
+ Added IP command and information on its use. Generally ifconfig is considered as depreciated in some circles.
+ Added info for the IP route command
+ Added ip command for showing arp cache
=> added ip command

lessons/locales/en_english/filesystem/symlinks.md, lessons/locales/en_english/getting-started/arch-linux.md, lessons/locales/en_english/getting-started/gentoo.md, lessons/locales/en_english/init/systemd-overview.md, lessons/locales/en_english/kernel/kernel-overview.md, lessons/locales/en_english/network-fundamentals/network-layer.md, lessons/locales/en_english/network-troubleshooting/packet-analysis.md, lessons/locales/en_english/network-troubleshooting/traceroute.md, lessons/locales/en_english/processes/process-creation.md, lessons/locales/en_english/routing/path-of-a-packet.md, lessons/locales/en_english/text-fu-advanced/emacs-text-editor.md, lessons/locales/en_english/text-fu-advanced/vim-text-editor.md, lessons/locales/en_english/text-fu/sort-command.md, lessons/locales/en_english/text-fu/stderr-standard-error-redirect.md, lessons/locales/en_english/user-management/user-management-tools.md
I went through in github and did my best to correct it's/its errors.
=> Several typos, mostly it's -> its

lessons/locales_config/fr.yml
update FR translation in fr.yml
=> update FR translation in fr.yml

lessons/locales_config/es.yml
`Checar` is not a spanish word :P
=> Fix -Check Answer- button

lessons/locales_config/mk.yml
Hey! Awesome project. I added support on my language.
=> Macedonian lang. support added

lessons/locales/es_spanish/getting-started/arch-linux.md, lessons/locales/es_spanish/getting-started/choosing-a-linux-distribution.md, lessons/locales/es_spanish/getting-started/debian.md, lessons/locales/es_spanish/getting-started/fedora.md, lessons/locales/es_spanish/getting-started/gentoo.md, lessons/locales/es_spanish/getting-started/linux-history.md, lessons/locales/es_spanish/getting-started/linux-mint.md, lessons/locales/es_spanish/getting-started/red-hat-enterprise-linux.md, lessons/locales/es_spanish/getting-started/ubuntu.md
Add es_spanish locale for lesson 1 "Getting started"
=> Add lesson 1 spanish translation

lessons/locales/en_english/text-fu/uniq-unique-command.md
1. Added description about limitations of uniq command.
2. Added how to overcome that limitation using sort
=> [Upd] Limitation of uniq command when duplicate lines are not adjacent

lessons/locales/en_english/packages/package-install-tools.md
http://www.english-for-students.com/Discuss.html
=> [Fix] Grammar mistake in package-install-tools.md

lessons/locales_config/he.yml
This time without deleting anything else.
=> Added Hebrew translation

lessons/locales/fr_french/getting-started/arch-linux.md, lessons/locales/fr_french/getting-started/debian.md, lessons/locales/fr_french/getting-started/fedora.md, lessons/locales/fr_french/getting-started/gentoo.md, lessons/locales/fr_french/getting-started/linux-history.md, lessons/locales/fr_french/getting-started/linux-mint.md, lessons/locales/fr_french/getting-started/openSUSE.md, lessons/locales/fr_french/getting-started/red-hat-enterprise-linux.md, lessons/locales/fr_french/getting-started/ubuntu.md
- debian.md
- linux-history.md
1. arch-linux.md
2. fedora.md
3. gentoo.md
4. linux-mint.md
5. openSUSE.md
6. red-hat-enterprise-linux.md
7. ubuntu.md
=> End translation getting-started into french

lessons/locales/en_english/process-utilization/process-threads.md
As we learn Linux there is no Microsoft Word,
so seems inappropriate example kind of
imho
=> [Upd] Update process-threads.md

lessons/locales/en_english/logging/system-logging.md
=> [Fix] Fix system-logging.md

lessons/locales/en_english/network-fundamentals/link-layer.md
=> [Fix] Typo in link-layer.md

lessons/locales/fr_french/command-line/alias-command.md, lessons/locales/fr_french/command-line/cat-command.md, lessons/locales/fr_french/command-line/change-directory-cd-command.md, lessons/locales/fr_french/command-line/copy-cp-command.md, lessons/locales/fr_french/command-line/exit-command.md, lessons/locales/fr_french/command-line/file-command.md, lessons/locales/fr_french/command-line/find-command.md, lessons/locales/fr_french/command-line/help-command.md, lessons/locales/fr_french/command-line/history-command.md, lessons/locales/fr_french/command-line/less-command.md, lessons/locales/fr_french/command-line/list-directories-ls-command.md, lessons/locales/fr_french/command-line/make-directory-mkdir-command.md, lessons/locales/fr_french/command-line/man-command.md, lessons/locales/fr_french/command-line/move-mv-command.md, lessons/locales/fr_french/command-line/print-working-directory-pwd-command.md, lessons/locales/fr_french/command-line/remove-rm-command.md, lessons/locales/fr_french/command-line/the-shell.md, lessons/locales/fr_french/command-line/touch-command.md, lessons/locales/fr_french/command-line/whatis-command.md
=> Translation "Command Line" course

lessons/locales/sk_slovak/getting-started/arch-linux.md, lessons/locales/sk_slovak/getting-started/choosing-a-linux-distribution.md, lessons/locales/sk_slovak/getting-started/debian.md, lessons/locales/sk_slovak/getting-started/fedora.md, lessons/locales/sk_slovak/getting-started/gentoo.md, lessons/locales/sk_slovak/getting-started/linux-history.md, lessons/locales/sk_slovak/getting-started/linux-mint.md, lessons/locales/sk_slovak/getting-started/red-hat-enterprise-linux.md, lessons/locales/sk_slovak/getting-started/ubuntu.md, lessons/locales_config/sk.yml
Hi, I started the Slovak translation, It's my first pull requeste ever, so I hope it will be acceptable.
=> Add slovak translation support, slovak translation of Getting Started

lessons/locales/en_english/process-utilization/memory-monitoring.md
Makes this section consistent with the others.
=> Include field abbreviations for vmstat system fields

lessons/locales_config/kr.yml
Added Main Page Korean Translation
Chagned en to kr
=> Added Main Page Korean Translation

lessons/locales/kr_korean/home_page.md
added locales/kr_korean 
and translated home_page.md into korean
=> translate main page english -> korean

lessons/locales/fr_french/home_page.md
=> add FR translation home_page.md

lessons/locales/fr_french/command-line/alias-command.md, lessons/locales/fr_french/command-line/cat-command.md, lessons/locales/fr_french/command-line/change-directory-cd-command.md, lessons/locales/fr_french/command-line/copy-cp-command.md, lessons/locales/fr_french/command-line/exit-command.md, lessons/locales/fr_french/command-line/file-command.md, lessons/locales/fr_french/command-line/find-command.md, lessons/locales/fr_french/command-line/help-command.md, lessons/locales/fr_french/command-line/history-command.md, lessons/locales/fr_french/command-line/less-command.md, lessons/locales/fr_french/command-line/list-directories-ls-command.md, lessons/locales/fr_french/command-line/make-directory-mkdir-command.md, lessons/locales/fr_french/command-line/man-command.md, lessons/locales/fr_french/command-line/move-mv-command.md, lessons/locales/fr_french/command-line/print-working-directory-pwd-command.md, lessons/locales/fr_french/command-line/remove-rm-command.md, lessons/locales/fr_french/command-line/the-shell.md, lessons/locales/fr_french/command-line/touch-command.md, lessons/locales/fr_french/command-line/whatis-command.md, lessons/locales/fr_french/getting-started/choosing-a-linux-distribution.md, lessons/locales/fr_french/getting-started/debian.md, lessons/locales/fr_french/getting-started/fedora.md, lessons/locales/fr_french/getting-started/linux-history.md, lessons/locales/fr_french/getting-started/linux-mint.md, lessons/locales/fr_french/getting-started/openSUSE.md, lessons/locales/fr_french/getting-started/red-hat-enterprise-linux.md, lessons/locales/fr_french/getting-started/ubuntu.md
=> [FR] Translation correction

lessons/locales/kr_korean/getting-started/linux-history.md
Translate Linux-History
From English to Korean
=> Translate Linux-History.md EN -> KR

lessons/locales/tr_turkish/getting-started/choosing-a-linux-distribution.md, lessons/locales/tr_turkish/getting-started/debian.md, lessons/locales/tr_turkish/getting-started/linux-history.md, lessons/locales_config/tr.yml
Debian and choosing-a-linux translation has been completed. Some typos corrected.
=> [TR] Debian and choosing-a-linux translation

lessons/locales/en_english/network-troubleshooting/traceroute.md
Somehow the word "are" was twice in the first sentence
=> Remove redundand "are"

lessons/locales/en_english/filesystem/anatomy-of-a-disk.md
This commit changes some of the sentence structure for a better reading flow.
=> Update some of the Filesystem/Anatomy grammar

lessons/locales/en_english/routing/what-is-a-router.md
Packet SWITCHING is basically receiving, processing and forwarding data to the destination device.
ROUTING is a process of creating the routing table, so that we can do SWITCHING better.
Before routing, FLOODING was used. If a router don't know which way to send a packet than every incoming packet is sent through every outgoing link except the one it arrived on.
=> Switching, Routing & Flooding?

lessons/locales/en_english/command-line/help-command.md
Corrects the grammar in the `help` tutorial in the command-line section.
This correction should make reading the tutorial a bit easier to read.
=> Correct grammar in the help command narrative

lessons/locales/de_german/getting-started/fedora.md
- Remove typo from heading: `Ihalt` -> `Inhalt`
=> Remove typo from fedora.md
